' GENERATED FILE — DO NOT EDIT.
' Source: design/viptv-design-system/tokens/tokens.json
' Regenerate: node design/viptv-design-system/tools/gen-themes.mjs

' Roku SceneGraph colours are 0xRRGGBBAA strings.
function ViptvTokens() as object
    return {
        color_bg: "0x0B0B0CFF"
        color_bg_oled: "0x000000FF"
        color_surface_1: "0x161618FF"
        color_surface_2: "0x212124FF"
        color_surface_3: "0x2A2A2EFF"
        color_surface_4: "0x34343AFF"
        color_text_primary: "0xF4F2EEFF"
        color_text_body: "0xDAD8D3FF"
        color_text_secondary: "0xB6B4AFFF"
        color_text_tertiary: "0x8F8D89FF"
        color_on_light: "0x111113FF"
        color_on_accent: "0x15130FFF"
        color_accent_default: "0xF5C542FF"
        color_accent_options_gold: "0xF5C542FF"
        color_accent_options_coral: "0xFF8B5CFF"
        color_accent_options_mint: "0x62D9BCFF"
        color_accent_options_periwinkle: "0xA3BCFFFF"
        color_status_live: "0xFF5A4EFF"
        color_status_danger: "0xFF7A6EFF"
        color_status_danger_tv: "0xFF8A7EFF"
        color_status_spinner_track: "0x45454BFF"
        color_line_hairline: "0xFFFFFF12"
        color_line_chip: "0xFFFFFF1A"
        color_line_outline: "0xFFFFFF24"
        color_line_strong: "0xFFFFFF38"
        color_fill_tv_unfocused: "0xFFFFFF1F"
        color_fill_tv_selected: "0xFFFFFF29"
        color_fill_glass: "0x202023F0"
        color_fill_badge_glass: "0x0000008C"
        color_scrim_sheet: "0x0000009E"
        color_scrim_dialog: "0x0000008C"
        color_scrim_tv_panel: "0x00000099"
        color_scrim_tv_menu: "0x0000008C"
        color_scrim_tv_fullscreen: "0x0B0B0CF0"
        radius_xs: 4
        radius_sm: 8
        radius_field_titlebar: 9
        radius_md: 12
        radius_lg: 14
        radius_xl: 16
        radius_2xl: 18
        radius_3xl: 22
        radius_sheet: 28
        radius_phone_frame: 44
        layout_phone_gutter: 16
        layout_phone_top_inset: 58
        layout_phone_nav_height: 64
        layout_phone_nav_bottom: 28
        layout_phone_min_target: 44
        layout_phone_bottom_clearance: 140
        layout_desktop_titlebar: 40
        layout_desktop_rail: 84
        layout_desktop_dialog_width: 460
        layout_desktop_drawer_width: 460
        layout_desktop_popup_width: 340
        layout_tv_safe_x: 96
        layout_tv_safe_y: 54
        layout_tv_rail_collapsed: 144
        layout_tv_menu_expanded: 520
        layout_tv_panel_width: 820
        layout_tv_row_gap: 36
        layout_tv_heading_to_row: 22
        layout_tv_art_to_caption: 16
        size_button_phone: 54
        size_button_phone_detail: 58
        size_button_desktop: 48
        size_button_tv: 72
        size_button_tv_small: 52
        size_chip_phone: 44
        size_chip_desktop: 40
        size_chip_desktop_drawer: 36
        size_chip_tv: 56
        size_field_phone: 54
        size_field_desktop: 48
        size_field_desktop_titlebar: 30
        size_field_tv: 80
        size_field_radius_phone: 16
        size_field_radius_desktop: 12
        size_field_radius_tv: 20
        size_row_tv: 80
        size_progress_phone: 4
        size_progress_desktop: 4
        size_progress_tv: 6
    }
end function
