sub Main()
    library = SanitizeApiResponse("/api/profiles/1/favorites/page?limit=40&offset=40","GET",{items:[{id:"saved",type:"movie",name:"Saved"}],offset:40,total:42,next_offset:invalid})
    check(library.ok and library.data.items[0].id="saved" and library.data.offset=40,"library paging survives transport")
    toggle = SanitizeApiResponse("/api/profiles/1/favorites/toggle","POST",{ok:true,saved:false})
    check(toggle.ok and toggle.data.saved=false,"atomic favorite removal survives transport")
    check(not SanitizeApiResponse("/api/profiles/1/favorites/page","GET",{items:"bad",offset:0}).ok,"malformed library is rejected")
    check(not SanitizeApiResponse("/api/profiles/1/favorites/toggle","POST",{saved:"false"}).ok,"malformed toggle cannot change saved UI state")
    page = SanitizeApiResponse("/api/profiles/1/continue/page?limit=40","GET",{items:[{id:"opaque",type:"series",series_id:"show",queue_status:"next",position:0,source_addon_id:"iptv:1",source_release_group:"family",audio_language:"eng"}],offset:40,total:81,next_offset:80})
    check(page.ok and page.data.next_offset=80 and page.data.items[0].queue_status="next","queue envelope survives transport")
    check(page.data.items[0].audio_language="eng" and page.data.items[0].source_release_group="family","continuation hints survive transport")
    nextEpisode = SanitizeApiResponse("/api/profiles/1/continue/next","POST",{status:"next",item:{id:"real-id",type:"series",series_id:"show",season:2,episode:1,position:0}})
    check(nextEpisode.ok and nextEpisode.data.item.id="real-id","actual next identity survives transport")
    check(not SanitizeApiResponse("/api/profiles/1/continue/page","GET",{items:"bad",offset:0}).ok,"malformed queue rejected")
    replacement = {id:"logical",url:"/media/generation2/cap/index.m3u8",format:"hls",mode:"remux",position:0,live:true,managed_live:true,generation:2,channel_id:"family:east"}
    recovery = SanitizeApiResponse("/api/playback/logical/heartbeat","POST",{ok:true,managed_live:true,state:"playing",generation:2,playback:replacement})
    check(recovery.ok and recovery.data.generation = 2,"managed heartbeat preserves generation")
    check(recovery.data.playback.id = "logical" and recovery.data.playback.channel_id = "family:east","replacement retains logical session and channel")
    invalidRecovery = SanitizeApiResponse("/api/playback/logical/heartbeat","POST",{ok:true,managed_live:true,state:"playing",generation:3,playback:replacement})
    check(not invalidRecovery.ok,"mixed-generation replacement response rejected")
    recovery = SanitizeApiResponse("/api/playback/logical/recover","POST",{ok:true,managed_live:true,state:"recovering",generation:1})
    check(recovery.ok and recovery.data.state = "recovering","recovery wait does not require a premature playback URL")
    east = "family:cartoon-east"
    west = "family:cartoon-west"
    family = SanitizeApiResponse("/api/live", "GET", {channels:[{id:east,name:"Cartoon Network East",category:"Kids"},{id:west,name:"Cartoon Network West",category:"Kids"}],total:2})
    check(family.ok and family.data.channels.count() = 2,"family regional channels stay distinct in listing")
    check(family.data.channels[0].id = east and family.data.channels[1].id = west,"family identities survive Roku API sanitation")
    favorite = SanitizeApiResponse("/api/profiles/1/favorites","GET",[{id:east,type:"live",name:"Cartoon Network East"}])
    recent = SanitizeApiResponse("/api/profiles/1/progress","GET",[{id:west,type:"live",name:"Cartoon Network West",position:0,duration:0}])
    check(favorite.ok and favorite.data[0].id = east,"canonical favorites remain playable")
    check(recent.ok and recent.data[0].id = west,"recent live preserves West identity")
    play = PlaybackBody(recent.data[0],"1",invalid,0,false)
    check(play.channel_id = west and play.stream_id = invalid,"Roku requests logical family channel without provider substitution")
    check(ApiOrigin("https://tv.example.com/") = "https://tv.example.com","normalize origin")
    check(ApiOrigin("https://tv.example.com/path") = "","reject mount paths")
    check(ApiOrigin("https://user:pass@host") = "","reject embedded credentials")
    check(ApiOrigin("http://[::1]:8080") <> "","IPv6 origin")
    check(ApiOrigin("http://host:99999") = "","invalid port")
    result = SanitizeApiResponse("/api/meta/series/tt1","GET",{meta:{id:"tt1",type:"series",name:"Series",videos:[{id:"tt1:1:1",title:"Pilot",season:1,episode:1},invalid],unexpected:{nested:"drop"}}})
    check(result.ok and result.data.meta.videos.count() = 1,"episode schema")
    check(result.data.meta.unexpected = invalid,"nested metadata dropped")
    result = SanitizeApiResponse("/api/guide/channel","GET",{programs:[{title:"Valid",start:100,end:200},{title:"Invalid",start:"not time",end:200}]})
    check(result.ok and result.data.programs.count() = 1,"guide rejects invalid times")
    result = SanitizeApiResponse("/api/guide/family:one","GET",{timezone:"America/New_York",programs:[{title:"DST guide",start:100,end:200,display_time:"1:30 AM EST",display_date:"2026-11-01"}]})
    check(result.ok and result.data.programs[0].display_time = "1:30 AM EST", "guide preserves household DST label")
    playbackRequest = PlaybackBody({id:"stream-1",type:"movie"},"profile-must-not-cross-wire",invalid,30,false)
    check(playbackRequest.stream_id = "stream-1" and not playbackRequest.DoesExist("profile_id"),"playback request is scoped only by authenticated session profile")
    result = SanitizeApiResponse("/api/playback","POST",{id:"session",url:"/media/session/cap/index.m3u8",mode:"transcode",video_mode:"copy",audio_mode:"encode",format:"hls",position:600,duration:3600})
    check(result.ok and result.data.duration = 3600,"original duration retained")
    check(result.data.video_mode = "copy" and result.data.audio_mode = "encode","independent copy modes retained")
    result = SanitizeApiResponse("/api/playback","POST",{id:"live-session",url:"/media/live/index.m3u8",mode:"transcode",format:"hls",position:0,duration:invalid,live:true})
    check(result.ok and result.data.live and result.data.duration = invalid,"nullable duration and live flag retained safely")
    result = SanitizeApiResponse("/api/playback","POST",{id:"session",url:"file:/secret",mode:"unknown",format:"mkv",position:0})
    check(not result.ok,"unsupported playback rejected")
    result = SanitizeApiResponse("/api/streams/job?after=1","GET",{events:[{seq:2,streams:[]}],done:true})
    check(result.ok and result.data.events[0].seq = 2,"poll cursor typed")
    result = SanitizeApiResponse("/api/discover?type=movie","GET",{metas:"bad"})
    check(not result.ok,"invalid catalog envelope rejected")
    result = SanitizeApiResponse("/api/profiles","GET",[invalid,42,{id:1,name:"Viewer"}])
    check(result.ok and result.data.count() = 1,"collection scalar filtering")
    result = {ok:false,error:"",data:invalid,status:0}
    saved = ConfigRequest({body:{base:"https://tv.example",access_token:"paired-only",refresh_token:"rotate",last_profile_id:"1",auth_version:3,auth_origin:"https://tv.example"}},result,"CONFIG_SAVE")
    check(saved.ok and saved.data.access_token = "paired-only","paired account credential saves with origin proof")
    loaded = ConfigRequest({},result,"CONFIG_LOAD")
    check(loaded.ok and loaded.data.last_profile_id = "1" and loaded.data.token = invalid,"account-only config roundtrip has no static token field")
    registry = CreateObject("roRegistrySection","VIPTV")
    registry.delete("config")
    registry.flush()
    first = ApiResponseStem({request_id:"2-10"},7)
    second = ApiResponseStem({request_id:"2-11"},7)
    check(first <> second,"concurrent tasks isolate files despite reused transfer identity")
    check(ApiResponseStem({request_id:"../../secret"},7) = "tmp:/viptv-api-legacy-7","unsafe request identifiers cannot create paths")
    contextItem = ApiItem({id:"opaque-video",type:"series",name:"Canonical parent",series_id:"parent-42",season:2,episode:7,year:2021,releaseInfo:"2020–",imdb_id:"tt1234567",tmdb_id:3456,source_addon_id:"addon.stable",source_name:"Provider stable"})
    check(contextItem.series_id = "parent-42" and contextItem.season = 2 and contextItem.episode = 7,"opaque episode coordinates and parent survive schema")
    check(contextItem.year = 2021 and contextItem.imdb_id = "tt1234567" and contextItem.tmdb_id = "3456","numeric year and alternate IDs survive schema")
    result = SanitizeApiResponse("/api/profiles/viewer/progress","GET",[contextItem])
    resumed = result.data[0]
    check(result.ok and resumed.id = "opaque-video" and resumed.name = "Canonical parent","progress read retains original episode and canonical name")
    check(resumed.series_id = "parent-42" and resumed.tmdb_id = "3456" and resumed.year = 2021,"progress read retains matching context")
    resumeContext = StreamContext(resumed)
    check(resumeContext.series_id = "parent-42" and resumeContext.season = 2 and resumeContext.episode = 7 and resumeContext.year = 2021,"sanitized progress read produces complete opaque resume request context")
    invalidItem = ApiItem({id:"bad",series_id:{nested:true},season:1.5,episode:-2,year:2201,releaseInfo:2021,imdb_id:"not-imdb",tmdb_id:"12x"})
    check(invalidItem.series_id = invalid and invalidItem.season = invalid and invalidItem.episode = invalid,"bad parent and coordinates dropped")
    check(invalidItem.year = invalid and invalidItem.releaseInfo = invalid and invalidItem.imdb_id = invalid and invalidItem.tmdb_id = invalid,"invalid optional year and identity metadata dropped")
    invalidItem = ApiItem({year:"2021",season:true,episode:100001,imdb_id:{id:"tt1"},tmdb_id:1.25,series_id:chr(10) + "parent"})
    check(invalidItem.year = invalid and invalidItem.season = invalid and invalidItem.episode = invalid,"numeric matching fields require bounded integers")
    check(invalidItem.imdb_id = invalid and invalidItem.tmdb_id = invalid and invalidItem.series_id = invalid,"nested fractional and control-character IDs rejected")
    boundary = ApiItem({id:"original opaque episode",series_id:"opaque parent with spaces",season:0,episode:100000,year:1870,releaseInfo:string(128,"x"),imdb_id:"tt12345",tmdb_id:"2147483647"})
    check(boundary.id = "original opaque episode" and boundary.series_id = "opaque parent with spaces","opaque IDs and embedded spaces remain verbatim")
    check(boundary.season = 0 and boundary.episode = 100000 and boundary.year = 1870,"common numeric lower and upper boundaries accepted")
    check(len(boundary.releaseInfo) = 128 and boundary.imdb_id = "tt12345" and boundary.tmdb_id = "2147483647","common string and decimal boundaries accepted")
    boundary = ApiItem({series_id:string(512,"x"),year:2200,imdb_id:"tt123456789012"})
    check(len(boundary.series_id) = 512 and boundary.year = 2200 and boundary.imdb_id = "tt123456789012","parent ID year and IMDb maximums accepted")
    bad = ApiItem({series_id:string(513,"x"),releaseInfo:string(129,"x"),season:100001,year:1869,imdb_id:"tt1234",tmdb_id:"2147483648"})
    check(bad.series_id = invalid and bad.releaseInfo = invalid and bad.season = invalid and bad.year = invalid,"common field overflows rejected")
    check(bad.imdb_id = invalid and bad.tmdb_id = invalid,"IMDb lower length and TMDB overflow rejected")
    bad = ApiItem({imdb_id:"tt1234567890123",tmdb_id:"tmdb:123"})
    check(bad.imdb_id = invalid and bad.tmdb_id = invalid,"oversized IMDb and prefixed TMDB rejected")
    bad = ApiItem({tmdb_id:"00123"})
    check(bad.tmdb_id = invalid,"TMDB strings must be canonical decimal")
    derived = StreamContext({id:"opaque parent:100001:2",type:"series",releaseInfo:"1869"})
    check(derived.series_id = "opaque parent" and derived.season = invalid and derived.episode = 2 and derived.year = invalid,"derived matching fields use identical contract limits")
    raw = []
    for i = 0 to 109
        raw.push({id:"first"+i.toStr(),source:"torrentio",name:"Torrentio",title:"Film 2160p HDR"})
    end for
    raw.push({id:"late-iptv",source:"iptv",name:"IPTV",title:"Film"})
    raw.push({id:"late-pengu",source:"pengu",name:"Pengu",title:"Film"})
    result = SanitizeApiResponse("/api/streams/job?after=0","GET",{events:[{seq:1,streams:raw}],done:false})
    check(result.ok and result.data.events[0].streams.count() = 112,"Task preserves every bounded source instead of hiding candidates")
    found = {}
    for each item in result.data.events[0].streams
        found[item.id] = true
    end for
    check(found.doesExist("late-iptv") and found.doesExist("late-pengu"),"late groups survive Task boundary")
    rich = SanitizeApiResponse("/api/streams/job?after=0","GET",{events:[{seq:2,streams:[{id:"language-source",source:"addon:1",name:"Neutral",filename:"Movie.mkv",size_bytes:1073741824,reported_languages:["ita","fra"],audio_language_status:"unverified"}]}],done:true})
    candidate = rich.data.events[0].streams[0]
    check(candidate.filename = "Movie.mkv" and candidate.size_bytes = 1073741824,"dedicated source filename and size cross Task boundary")
    check(candidate.reported_languages.count() = 2 and candidate.reported_languages[0] = "ita" and candidate.audio_language_status = "unverified","explicit language report is retained instead of guessed from title")
    page = SanitizeApiResponse("/api/discover?type=movie&skip=20","GET",{metas:[{id:"next",type:"movie",name:"Next"}],has_more:true,next_skip:37,aggregated:false,max_catalogs:1,max_results:200})
    check(page.ok and page.data.metas.count() = 1 and page.data.has_more and page.data.next_skip = 37,"authoritative catalog cursor and continuation survive Task boundary")
    path = "tmp:/source-expired-schema.json"
    for each detail in ["Stream expired; discover again","Stream expired; discover again https://user:secret@example.test/asset","stream expired; discover again","Other error"]
        check(WriteAsciiFile(path,FormatJson({error:detail})),"stage synthetic bounded error fixture")
        parsed = ReadResponse(path,{ok:false,status:400,data:invalid,error:""},2097152)
        check(not parsed.ok and parsed.error = "HTTP 400" and parsed.data = invalid,"error body credentials never leave Task boundary")
        if detail = "Stream expired; discover again"
            check(parsed.sourceExpired = true,"actual Rust Axum error envelope maps internal expiry flag")
        else
            check(parsed.sourceExpired = invalid,"near matches and untrusted sourceExpired field cannot trigger discovery")
        end if
    end for
    check(not ApiSourceExpired(FormatJson({detail:"Stream expired; discover again"})),"wrong-framework detail envelope never classifies")
    check(not ApiSourceExpired(string(4097," ") + FormatJson({error:"Stream expired; discover again"})),"direct classifier also enforces bound")
    ignored = WriteAsciiFile(path,FormatJson({error:"Other error",sourceExpired:true,upstream:"https://user:secret@example.test/asset"}))
    parsed = ReadResponse(path,{ok:false,status:400,data:invalid,error:""},2097152)
    check(parsed.sourceExpired = invalid and parsed.data = invalid,"raw sourceExpired flag and extra fields never propagate")
    ignored = WriteAsciiFile(path,FormatJson({error:"Stream expired; discover again"}))
    check(ApiSourceExpired(chr(10) + FormatJson({error:"Stream expired; discover again"}) + chr(13)),"safe JSON whitespace accepted without parsing raw errors")
    check(not ApiSourceExpired(FormatJson({error:"Stream expired; discover again",upstream:"https://user:secret@example.test"})),"only the exact known JSON shape qualifies")
    for each status in [401,403,409,429,500]
        parsed = ReadResponse(path,{ok:false,status:status,data:invalid,error:""},2097152)
        check(parsed.sourceExpired = invalid and parsed.error = "HTTP " + status.toStr(),"expiry text cannot override auth capacity or other HTTP failures")
    end for
    ignored = WriteAsciiFile(path,FormatJson({error:"Stream expired; discover again",padding:string(4096,"x")}))
    parsed = ReadResponse(path,{ok:false,status:400,data:invalid,error:""},2097152)
    check(parsed.sourceExpired = invalid and parsed.error = "HTTP 400","oversized error does not enter classification parser")
    ignored = WriteAsciiFile(path,"not JSON https://user:secret@example.test")
    parsed = ReadResponse(path,{ok:false,status:400,data:invalid,error:""},2097152)
    check(parsed.sourceExpired = invalid and parsed.data = invalid,"nonJSON400 remains opaque")
    for each status in [0,-6,-35,-60]
        parsed = ReadResponse(path,{ok:false,status:status,data:invalid,error:""},2097152)
        check(parsed.error = "Network request failed (" + status.toStr() + ")", "closed numeric transport diagnostic")
        check(parsed.data = invalid and parsed.sourceExpired = invalid, "transport failure does not expose response body")
    end for
    ignored = WriteAsciiFile(path,FormatJson({error_code:"audio_language_unknown",error:"Audio language is unknown"}))
    policy = ReadResponse(path,{ok:false,status:400,data:invalid,error:""},2097152)
    check(policy.audioPolicy = invalid and policy.error = "HTTP 400" and policy.data = invalid,"Roku no longer classifies or gates language-policy failures")
    CreateObject("roFileSystem").delete(path)
    categories = SanitizeApiResponse("/api/live/categories?offset=80&limit=80","GET",{categories:[{id:"category:UK",name:"UK",count:12}],total:90})
    check(categories.ok and categories.data.categories[0].id = "category:UK" and categories.data.categories[0].count = 12,"category opaque IDs/count survive Task boundary")
    check(not SanitizeApiResponse("/api/live/categories","GET",{categories:[],total:-1}).ok,"invalid category total rejected")
    tracks = SanitizeApiResponse("/api/playback","POST",{id:"session",url:"/hls/test.m3u8",format:"hls",mode:"transcode",position:650,audio_tracks:[{input_index:2,language:"eng",title:"English stereo",selected:true,selectable:true,password:"discard"}],subtitle_tracks:[{input_index:4,language:"eng",selectable:false}],subtitles_supported:false,selected_subtitle:invalid,selected_audio:{input_index:2,output_index:0,language_status:"tagged_english"}})
    check(tracks.ok and tracks.data.audio_tracks[0].input_index = 2 and tracks.data.selected_audio.output_index = 0,"absolute input index retained separately from remapped output")
    check(tracks.data.audio_tracks[0].password = invalid and tracks.data.audio_tracks[0].selectable = true and tracks.data.subtitle_tracks[0].selectable = false and tracks.data.subtitles_supported = false,"track metadata bounded whitelisted and capability flag retained")
    print "ROKU_SCHEMA_OK"
end sub

sub check(condition as boolean,label as string)
    if not condition
        print "TEST_FAIL "; label
        stop
    end if
end sub
